/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WMeter;

import MyCode.DBConnect;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MNB
 */
public class BillPayment extends javax.swing.JInternalFrame {
    
    Connection con = null;
    java.sql.PreparedStatement pst = null;
    ResultSet rs = null;
    String item ="NIC Number";
    DateFormat dateFormat ;
    Calendar cal;
    String date;
    
    public BillPayment() {
       initComponents();
       con= DBConnect.connect();
        tableload();
           
    }
    
     
      public void tableload(){
        
        try{
        String q = "SELECT payment.accountnumber,payment.amount,customerdetail.user_name,customerdetail.nic_number,payment.date_time FROM payment,customerdetail WHERE customerdetail.accountnumber=payment.accountnumber";//SELECT accountnumber,nic_number,user_name,amount FROM payment
        //"SELECT payment.accountnumber,payment.amount,customerdetail.user_name,customerdetail.nic_number FROM payment,customerdetail WHERE customerdetail accountnumber=payment accountnumber;"
        pst = con.prepareStatement(q);
        rs = pst.executeQuery();
        jTableBP.setModel(DbUtils.resultSetToTableModel(rs));
        
                
                }
        catch(Exception e ){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBP = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        payment = new javax.swing.JTextField();
        Accnumber = new javax.swing.JLabel();
        Nicnumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NIcnumber = new javax.swing.JLabel();
        Uname = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DTime = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setTitle("SATSM");
        setPreferredSize(new java.awt.Dimension(850, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNameActionPerformed(evt);
            }
        });
        getContentPane().add(UName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 287, 32));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Enter Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 287, 37));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 130, 30));

        jTableBP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBP);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 220, 590, 218));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Search By");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 99, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIC Number", "User Name" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 185, 30));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 100, 24));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Account Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, 24));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Payment");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 115, 24));

        payment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 130, -1));

        Accnumber.setBackground(new java.awt.Color(255, 0, 51));
        Accnumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Accnumber.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(Accnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 160, 20));
        getContentPane().add(Nicnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 89, -1, 45));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("NIC Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 100, 22));

        NIcnumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(NIcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 120, 20));

        Uname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(Uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 120, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Date and Time");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 100, 20));

        DTime.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(DTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 170, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WMeter/99.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNameActionPerformed
          
    }//GEN-LAST:event_UNameActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     item = jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       if(item.equals("NIC Number")){
            
       String user = UName.getText();
       
       String sql = "SELECT payment.accountnumber,payment.amount,customerdetail.user_name,customerdetail.nic_number,payment.date_time FROM payment,customerdetail WHERE customerdetail.accountnumber=payment.accountnumber AND customerdetail.nic_number LIKE '%"+user+"%'";
       //customerdetail//customerdetail nic_number LIKE '%"+user+"%'
       
       try{
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        jTableBP.setModel(DbUtils.resultSetToTableModel(rs));
        
       }
       catch(Exception e){
           System.out.println(e);
       }
       }
        
      else
        {
       String user = UName.getText();
       
       String sql =  "SELECT payment.accountnumber,payment.amount,customerdetail.user_name,customerdetail.nic_number,payment.date_time FROM payment,customerdetail WHERE customerdetail.accountnumber=payment.accountnumber AND customerdetail.user_name LIKE '%"+user+"%'";
       
       try{
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        jTableBP.setModel(DbUtils.resultSetToTableModel(rs));
       
       }
       catch(Exception e){
           
       }
        
        }
                                           
           
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         tableload();
          
         
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableBPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBPMouseClicked
        int r = jTableBP.getSelectedRow();
        String acn= jTableBP.getValueAt(r, 0).toString();
        String username =jTableBP.getValueAt(r, 2).toString();
        String Payment = jTableBP.getValueAt(r, 1).toString();
        String nicnumber = jTableBP.getValueAt(r, 3).toString();
        String date = jTableBP.getValueAt(r, 4).toString();
        
       
        Uname.setText(username);
        payment.setText(Payment); 
        Accnumber.setText(acn);
        NIcnumber.setText(nicnumber);
        DTime.setText(date);
    }//GEN-LAST:event_jTableBPMouseClicked
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accnumber;
    private javax.swing.JLabel DTime;
    private javax.swing.JLabel NIcnumber;
    private javax.swing.JLabel Nicnumber;
    private javax.swing.JTextField UName;
    private javax.swing.JLabel Uname;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBP;
    private javax.swing.JTextField payment;
    // End of variables declaration//GEN-END:variables
}
