/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WMeter;

import MyCode.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MNB
 */
public class Payment extends javax.swing.JFrame {
        Connection con = null;
        PreparedStatement pst =null; 
        ResultSet rs = null;
        String bb;
        DateFormat dateFormat ;
        Calendar cal;
        String Anumber; 
        
public static void main(){
    SError SE = new SError();
    System.out.println();
    

}
    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
             con = DBConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        account_number = new javax.swing.JTextField();
        Nicnumber = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        btnSbmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SATSM");
        setPreferredSize(new java.awt.Dimension(420, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Bill Payment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 275, 28));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 124, 28));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Account Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 124, 28));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Amount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 124, 28));

        account_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                account_numberActionPerformed(evt);
            }
        });
        getContentPane().add(account_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 143, 28));

        Nicnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NicnumberActionPerformed(evt);
            }
        });
        getContentPane().add(Nicnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 143, 28));

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 143, 28));

        btnSbmit.setText("Submit");
        btnSbmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSbmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSbmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 345, 104, 38));

        btnCancel.setText("Clear");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 345, 99, 38));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 345, 81, 39));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("NIC Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 84, 22));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 143, 28));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WMeter/99.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      clearField();
      
    }//GEN-LAST:event_btnCancelActionPerformed
   
    private void btnSbmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSbmitActionPerformed
        String nicnumber = Nicnumber.getText();     
        String Uname = username.getText(); 
        String Amount = amount.getText().toString(); 
        Anumber = account_number.getText().toString();
        
        dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
         Calendar cal = Calendar.getInstance();
         String date = (dateFormat.format(cal.getTime())); //2016/11/16 12:08:43
         System.out.println(date);
          if(Uname.equals("")){
              JOptionPane.showMessageDialog(this,"Complete all details");
          } 
          else if(Anumber.equals("")){
              JOptionPane.showMessageDialog(this,"Complete all details");
          } 
          else if(Amount.equals("")){
              JOptionPane.showMessageDialog(this,"Complete all details");
          } 
          else if(nicnumber.equals("")){
              JOptionPane.showMessageDialog(this,"Complete all details");
          } 
          else
          
            //("yyyy/MM/dd HH:mm:ss");  
              
             try{
                
            String q = "INSERT INTO payment (amount,nic_number,date_time,accountnumber) values ('"+Amount+"','"+nicnumber+"','"+date+"','"+Anumber+"')"; 
           //,nic_number,user_name//'"+nicnumber+"','"+Uname+"',
            pst = con.prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(this,"Sucsessfully inserted"); 
           // clearField();
            //this.dispose();
             System.out.println("this is entering...");
                
           
        }
        catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Error,Enter again correctly");
           // clearField();
        }
      
       try{
           Statement st = con.createStatement();
           String b ="SELECT accountnumber, sum(amount) as amount FROM payment GROUP BY accountnumber "; 
           //,nic_number,user_name//'"+nicnumber+"','"+Uname+"',";
         //pst = con.prepareStatement(b);
        //pst.execute();
        ResultSet rs = st.executeQuery(b);

  while(rs.next()) { 
      
            String tamount = rs.getString("amount");
            int Tamount = Integer.parseInt(tamount);
            System.out.print(tamount+"this is amount");
            String taccountnumber = rs.getString("accountnumber");
            int Taccountnumber = Integer.parseInt(taccountnumber);
            System.out.print(taccountnumber +"this is account number");
           try{
           Statement st1 = con.createStatement();
           //String d ="DELETE FROM totalaccount WHERE accountnumbe="+ taccountnumber+"";
          // pst = con.prepareStatement(d);
          // pst.execute();
          /// System.out.print("while erroo");
            try{
            String a = "INSERT INTO totalaccount(amount,accountnumber) values ('"+Tamount+"','"+Taccountnumber+"')"; 
            pst = con.prepareStatement(a);
            pst.execute();
             System.out.print("xxxxxxxxxxx");
             System.out.println(" ");
            }

catch(Exception e){
             System.out.print("catch..........");
            String a = "UPDATE totalaccount SET amount ='"+Tamount+"' WHERE accountnumber ='"+Taccountnumber+"'"; 
            pst = con.prepareStatement(a);
            pst.execute();
             // System.out.print(e);



}
           }
            catch(Exception e){
                
                System.out.println("down catch");
            }
           
           
}       
               }
       catch(Exception e){
           System.out.println("2 down catch");
           System.out.println(e);
}
       
               
               
              
              
        
                
                
    }//GEN-LAST:event_btnSbmitActionPerformed
    public void clearField(){
         Nicnumber.setText("");
         account_number.setText("");
         amount.setText("");
         Nicnumber.setText("");
         username.setText("");
    
    }
    private void NicnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NicnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NicnumberActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void account_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_account_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_account_numberActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nicnumber;
    private javax.swing.JTextField account_number;
    private javax.swing.JTextField amount;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSbmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
