/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package WMeter;

import MyCode.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author MNB
 */
public class SError extends javax.swing.JInternalFrame {

    /**
     * Creates new form SError
     */
    Connection con = null;
    PreparedStatement pst = null;
    PreparedStatement Rpst = null;
    ResultSet rs = null;
    ResultSet Rrs = null;
    String item ="NIC Number";
    ResultSetMetaData rsmd = null;
    String Caccountnumber;
    int Tprice;
    int Tbalance;
    int v;  
    
    public SError() {
        initComponents();
        con= DBConnect.connect();
        tableload();
        getdetail();
    }
      public void tableload(){
        
        try{
        String q = "SELECT account.accountnumber,account.ph_value,account.color,account.price FROM wmeter,account WHERE wmeter.accountnumber=account.accountnumber";
              //  "SELECT account.total_price,account.accountnumber,account.ph_value,account.color,account.speed,account.total_units,wmeter.balance FROM account,wmeter where account.accountnumber=wmeter.accountnumber";
        pst = con.prepareStatement(q);
        rs = pst.executeQuery();
        jTableER.setModel(DbUtils.resultSetToTableModel(rs));
       
                
                }
        catch(Exception e ){
            System.out.println(e);
              System.out.println("is this");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSBalance = new javax.swing.JButton();
        UName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableER = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        bBalance = new javax.swing.JLabel();
        lblacc = new javax.swing.JLabel();
        lbltxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setTitle("SATSM");
        setPreferredSize(new java.awt.Dimension(700, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSBalance.setText("Search balance");
        btnSBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSBalanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnSBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 130, 30));

        UName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNameActionPerformed(evt);
            }
        });
        getContentPane().add(UName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 275, 35));

        jTableER.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableER);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 225, 544, 138));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Search By");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 107, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIC Number", "User Name" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, 30));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 130, 30));

        label.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        label.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 120, 40));

        bBalance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bBalance.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(bBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 110, 30));
        getContentPane().add(lblacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 100, 30));
        getContentPane().add(lbltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 100, 30));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 130, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WMeter/99.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       item = jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed
      
    
    
    
    
    private void btnSBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSBalanceActionPerformed
    
        
       if(item.equals("NIC Number")){
            
       String user = UName.getText();
       System.out.print(user);
       String sql = "SELECT customerdetail.nic_number,account.accountnumber,account.total_units,wmeter.total_price,totalaccount.amount,wmeter.balance FROM totalaccount,account,wmeter,customerdetail where account.accountnumber=totalaccount.accountnumber AND account.accountnumber=wmeter.accountnumber AND account.accountnumber=customerdetail.accountnumber AND customerdetail.nic_number LIKE '%"+user+"%'";
       //,wmeter.balance //that table should be include pdate method wmeter
      
       try{
        
       pst = con.prepareStatement(sql);  
       rs = pst.executeQuery();
       jTableER.setModel(DbUtils.resultSetToTableModel(rs));
       
       String Bbalance = jTableER.getValueAt(v, 5).toString();
        
        label.setText("Balance");
        System.out.println(Bbalance);
       bBalance.setText(Bbalance); 
       
       lblacc.setText("NIC Number"); 
       String a =UName.getText();
       lbltxt.setText(a);
        System.out.print("this is ok...");
        System.out.print(Tbalance);
        UName.setText("");
       
       }
       catch(Exception e){
           System.out.println(e);
            System.out.println("okkkk1111111111");
       }
        }
        
      else
        {
       String user = UName.getText();
       
       String sql = "SELECT customerdetail.user_name,account.accountnumber,account.total_units,wmeter.total_price,totalaccount.amount,wmeter.balance FROM totalaccount,account,wmeter,customerdetail where account.accountnumber=totalaccount.accountnumber AND account.accountnumber=wmeter.accountnumber AND account.accountnumber=customerdetail.accountnumber AND customerdetail.user_name LIKE '%"+user+"%'";
       //,wmeter.balance//that table should be include pdate method wmeter
       try{
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        jTableER.setModel(DbUtils.resultSetToTableModel(rs));
        
        String Bbalance = jTableER.getValueAt(v, 5).toString();
        label.setText("Balance"); 
        bBalance.setText(Bbalance);
        
       lblacc.setText("User Name"); 
       String b =UName.getText();
       lbltxt.setText(b);
       UName.setText("");
       
       }
       catch(Exception e){
           System.out.print(e);
       }
       
        }
       
  
    }//GEN-LAST:event_btnSBalanceActionPerformed
 
public void getdetail(){
    
try{

Statement st = con.createStatement();
String sql = ("SELECT account.ph_value,account.color,account.price,account.accountnumber,totalaccount.amount,account.total_units FROM account,totalaccount WHERE totalaccount.accountnumber=account.accountnumber;");
ResultSet rs = st.executeQuery(sql);

 while(rs.next()) { 
// int id = rs.getInt("first_column_name"); 
  String tamount = rs.getString("amount");
  int Tamount = Integer.parseInt(tamount);
  System.out.print(tamount+" ");
  String acn = rs.getString("accountnumber");
  System.out.print(acn+" ");
  String unit = rs.getString("total_units");
  System.out.print(unit+"++++++=======++++ ");
  int Tunits = Integer.parseInt(unit);
  int unitprice=5;
  //int TotalPrice =  Tunits*unitprice;
   String TPrice = rs.getString("price");
   int TotalPrice = Integer.parseInt(TPrice);
   Tbalance = (Tamount-TotalPrice);
   System.out.print(TotalPrice+" ");
   System.out.print(Tbalance+" ");
  
  
  try{  
      
      
        String q = "INSERT INTO wmeter(accountnumber,unit_price,total_units,total_price,balance)values('"+acn+"','"+unitprice+"','"+Tunits+"','"+TotalPrice+"','"+Tbalance+"')"; 
           //,nic_number,user_name//'"+nicnumber+"','"+Uname+"',
            pst = con.prepareStatement(q);
            pst.execute();
             System.out.println("hhhhhhhhhhhhhhhh");
           
        }
        catch(Exception e){
           // System.out.println(e);
            //System.out.println("hey...balance...........");
            String q = "UPDATE wmeter SET unit_price='"+unitprice+"',total_units='"+Tunits+"',total_price='"+TotalPrice+"',balance='"+Tbalance+"' WHERE accountnumber='"+acn+"'"; 
           //,nic_number,user_name//'"+nicnumber+"','"+Uname+"',
            pst = con.prepareStatement(q);
            pst.execute();
            // System.out.println("test");
            
           
        }  
}
}

catch(Exception e){
System.out.print(e);
}


    
    }
    private void UNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         tableload();
        // mymethod();
        label.setText(""); 
        bBalance.setText("");
       lblacc.setText(""); 
       lbltxt.setText("");
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       getdetail();
       tableload();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UName;
    private javax.swing.JLabel bBalance;
    private javax.swing.JButton btnSBalance;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableER;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblacc;
    private javax.swing.JLabel lbltxt;
    // End of variables declaration//GEN-END:variables
}
/*{

 try{
        String Rq = "SELECT wmeter.accountnumber,payment.amount FROM payment,wmeter WHERE wmeter.accountnumber=payment.accountnumber";//SELECT accountnumber,nic_number,user_name,amount FROM payment

        Rpst = con.prepareStatement(Rq);
        Rrs = pst.executeQuery();
      //  jTableBP.setModel(DbUtils.resultSetToTableModel(rs));
        //rsmd= Rrs.getMetaData();
        int b = 2;
        String pAmount = Rrs.getString(i);
        System.out.print(pAmount);
        
                
                }
        catch(Exception e ){
            System.out.println(e);
             System.out.println("this is the palce");
        }
}*/